name: Test Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-app:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test database connection
        run: |
          python -c "import sqlalchemy; from dotenv import load_dotenv; load_dotenv(); from sqlalchemy import create_engine; import os; engine = create_engine(os.environ['DATABASE_URL']); conn = engine.connect(); print('Conexión exitosa a la base de datos'); conn.close()"
      - name: Test Streamlit app syntax
        run: |
          python -m py_compile app.py 